services:
  app:
    image: ${IMAGE_NAME:-ci-cd-lab}:${IMAGE_TAG:-local-compose}
    build: .
    container_name: ci-cd-lab-app
    ports:
      - "8000:8000"
    environment:
      APP_VERSION: ${APP_VERSION:-local-compose}
      IMAGE_TAG: ${IMAGE_TAG:-local-compose}
      DB_PATH: /data/tasks.db
    volumes:
      - ci_cd_lab_data:/data
    restart: unless-stopped

volumes:
  ci_cd_lab_data:
