services:
  app:
    build: .
    container_name: ci-cd-lab-app
    ports:
      - "8000:8000"
    environment:
      APP_VERSION: ${APP_VERSION:-local-compose}
      IMAGE_TAG: ${IMAGE_TAG:-local-compose}
    volumes:
      - ./tasks.db:/app/tasks.db
    restart: unless-stopped
